# frozen_string_literal: true

#
# par/rake_tasks.rb - Custom Rake tasks for PAR module
#
# This file provides custom rake tasks for the PAR module that supplement
# PDK's standard tasks. To use these tasks, add the following line to your
# Rakefile:
#
#   require 'par/rake_tasks' if File.exist?(File.join(__dir__, 'lib/par/rake_tasks.rb'))
#
# This approach ensures custom tasks persist across PDK updates since the
# Rakefile can be regenerated by PDK, but this file remains untouched.
#

# Cucumber acceptance tests
if Gem.loaded_specs.key?('cucumber')
  require 'cucumber/rake/task'

  namespace :acceptance do
    desc 'Run Cucumber acceptance tests (use FEATURE=path/to/feature.feature for specific test)'
    Cucumber::Rake::Task.new(:cucumber) do |t|
      # Allow running specific feature with FEATURE environment variable
      # Example: rake acceptance FEATURE=spec/acceptance/par_basic.feature
      feature_path = ENV['FEATURE'] || 'spec/acceptance'

      t.cucumber_opts = [
        feature_path,
        '--require', 'spec/acceptance/step_definitions',
        '--require', 'spec/acceptance/support',
        '--format', 'pretty'
      ]
    end

    desc 'Run Cucumber acceptance tests with HTML report'
    Cucumber::Rake::Task.new(:html) do |t|
      feature_path = ENV['FEATURE'] || 'spec/acceptance'

      t.cucumber_opts = [
        feature_path,
        '--require', 'spec/acceptance/step_definitions',
        '--require', 'spec/acceptance/support',
        '--format', 'pretty',
        '--format', 'html',
        '--out', 'acceptance_report.html'
      ]
    end
  end

  desc 'Run all acceptance tests (Cucumber) - use FEATURE=path for specific test'
  task acceptance: 'acceptance:cucumber'

  puts 'PAR custom rake tasks loaded (acceptance tests available)'
else
  puts 'Cucumber gem not loaded - acceptance test tasks unavailable'
end
